function savePublic(results, results_mol, results_graph,res_folder)
%SAVEPUBLIC save results in public.csv

for k=1:length(results)
    strMod{k} = results{k}.modality;
end

strMod = unique(strMod);

fname = 'public.csv';
if isempty(results_graph)
    results_graph = fill_results_graph(results);
end

initLen = length(results_graph);

for m=1:length(strMod)
    fileID = fopen(strcat(res_folder,filesep,...
        results{1}.participant,filesep, strMod{m},filesep,fname),'w');
    
    formatSpec = strcat('%s,%s,%s,%s,%f,%f,%i,%i,%i,%i,%i,',...%FN
        '%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,',...%Dz
        '%f,%f,%f,%f,%f,%f,%f,%f,%f,',...%SNRxy
        '%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,',...%Detection ratio_mol
        '%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,',...%max_z_range
        '%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,',...%stdRMSExy_onRangeZ
        '%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,',...%CVRMSExy_onRangeZ
        '%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,',...%FWHM Jaccard
        '%f,%f,%f,%f,','\n');%T2 Jaccard
    
    fprintf(fileID,strcat('Dataset,Density,',...
        'Modality,','Wobble,','TolXY,','TolZ,',...
        '# Fluorophores Test,','Thres Photon,',...
        'TP,','FP,','FN,','Jaccard,','F-Score,','Recall,','Precision,',...
        'RMSExyz,','RMSExy,','RMSEz,',...
        'MADxyz,','MADxy,','MADz,',...
        'Dx,','Dy,','Dz,','Corr. photons,',...
        'FSC,','FRCyz,','FRCxz,','FRCxy,',...
        'SNRxyz,','SNRyz,','SNRxz,','SNRxy,',...
        'TP_mol,','FN_mol,','Recall_mol,','RMSExyz_mol,','RMSExy_mol,','RMSEz_mol,',...
        'MADxyz_mol,','MADxy_mol,','MADz_mol,',...
        'Detection ratio_mol,',...
        'Min Z Recall T1,','Max Z Recall T1,',...
        'Mean RMSExy Recall T1,','STD RMSExy Recall T1,',...
        'Mean + STD RMSExy Recall T1,','CV RMSExy Recall T1,',...
        'Mean RMSEz Recall T1,','STD RMSEz Recall T1,',...
        'Mean + STD RMSEz Recall T1,','CV RMSEz Recall T1,',...
        'Min Z Recall T2,','Max Z Recall T2,',...
        'Mean RMSExy Recall T2,','STD RMSExy Recall T2,',...
        'Mean + STD RMSExy Recall T2,','CV RMSExy Recall T2,',...
        'Mean RMSEz Recall T2,','STD RMSEz Recall T2,',...
        'Mean + STD RMSEz Recall T2,','CV RMSEz Recall T2,',...
        'Min Z Jaccard T1,','Max Z Jaccard T1,',...
        'Mean RMSExy Jaccard T1,','STD RMSExy Jaccard T1,',...
        'Mean + STD RMSEz Recall T2,','CV RMSExy Jaccard T1,',...
        'Mean RMSEz Jaccard T1,','STD RMSEz Jaccard T1,',...
        'Mean + STD RMSEz Jaccard T1,','CV RMSEz Jaccard T1,',...
        'Min Z Jaccard T2,','Max Z Jaccard T2,',...
        'Mean RMSExy Jaccard T2,','STD RMSExy Jaccard T2,',...
        'Mean + STD RMSExy Jaccard T2,','CV RMSExy Jaccard T2,',...
        'Mean RMSEz Jaccard T2,','STD RMSEz Jaccard T2,',...
        'Mean + STD RMSEz Jaccard T2,','CV RMSEz Jaccard T2,',...
        'Range Z Recall T1,','Range Z Recall T2,',...
        'Range Z Jaccard T1,','Range Z Jaccard T2,',...
        'Max Recall,','min Z FWHM Recall,','max Z FWHM Recall,','FWHM Recall,',...
        'Max Jaccard,','min Z FWHM Jaccard,','max Z FWHM Jaccard,','FWHM Jaccard,',...
        'T1 Recall,','T2 Recall,','T1 Jaccard,','T2 Jaccard,','\n'));
    
    for k=1:length(results)
        l=1;
        notFound = true;
        while l <= initLen && notFound
            if strcmp(results_graph{l}.modality, results{k}.modality)...
                    && strcmp(results_graph{l}.dataset, results{k}.dataset)...
                    && strcmp(results_graph{l}.participant, results{k}.participant)...
                    && strcmp(results_graph{l}.wobble, results{k}.wobble)...
                    && results_graph{l}.photonT==results{k}.photonT
                    %&& ((strcmp(results_graph{l}.modality, '2D') && results{k}.dim3D==0)...
                    %|| (~strcmp(results_graph{l}.modality, '2D') && results{k}.dim3D==1))
                notFound = false;
            else
                l = l + 1;
                if l > initLen && length(results_graph)==initLen
                    for fn = fieldnames(results_graph{l-1})'
                        results_graph{l}.(fn{1}) = nan(size(results_graph{l}.(fn{1})));
                    end
                end
            end
        end
        if strcmp(results{k}.modality,strMod{m})
            fprintf(fileID,formatSpec,...
                results{k}.dataset,results{k}.dataset(end-1:end),...
                results{k}.modality,results{k}.wobble,...
                results{k}.radTolXY,results{k}.radTolZ,...
                results{k}.nloc_test_initial,...
                results{k}.photonT,...
                results{k}.TP,results{k}.FP,results{k}.FN,...
                results{k}.Jaccard,results{k}.Fscore,results{k}.recall,results{k}.precision,...
                results{k}.RMSExyz,results{k}.RMSExy,results{k}.RMSEz,...
                results{k}.MADxyz,results{k}.MADxy,results{k}.MADz,results{k}.distX,...
                results{k}.distY,results{k}.distZ,results{k}.corrPhoton,...
                results{k}.FSC,results{k}.FRC{1},results{k}.FRC{2},results{k}.FRC{3},...
                results{k}.SNR{1},results{k}.SNR{2},...
                results{k}.SNR{3},results{k}.SNR{4},...
                results_mol{k}.TPmol,results_mol{k}.FNmol,...
                results_mol{k}.recall_mol,...
                results_mol{k}.RMSExyz_mol,results_mol{k}.RMSExy_mol,results_mol{k}.RMSEz_mol,...
                results_mol{k}.MADxyz_mol,results_mol{k}.MADxy_mol,results_mol{k}.MADz_mol,...
                results_mol{k}.ratio_det_per_mol_ave,...
                results_graph{l}.min_z_range_metric(1, 1),...
                results_graph{l}.max_z_range_metric(1, 1),...
                results_graph{l}.meanRMSExy_onRangeZ(1, 1),...
                results_graph{l}.stdRMSExy_onRangeZ(1, 1),...
                results_graph{l}.meanRMSExy_onRangeZ(1, 1)...
                +results_graph{l}.stdRMSExy_onRangeZ(1, 1),...
                results_graph{l}.CVRMSExy_onRangeZ(1, 1),...
                results_graph{l}.meanRMSEz_onRangeZ(1, 1),...
                results_graph{l}.stdRMSEz_onRangeZ(1, 1),...    
                results_graph{l}.meanRMSEz_onRangeZ(1, 1)...
                +results_graph{l}.stdRMSEz_onRangeZ(1, 1),...
                results_graph{l}.CVRMSEz_onRangeZ(1, 1),...
                results_graph{l}.min_z_range_metric(1, 2),...
                results_graph{l}.max_z_range_metric(1, 2),...
                results_graph{l}.meanRMSExy_onRangeZ(1, 2),...
                results_graph{l}.stdRMSExy_onRangeZ(1, 2),...
                results_graph{l}.meanRMSExy_onRangeZ(1, 2)...
                +results_graph{l}.stdRMSExy_onRangeZ(1, 2),...
                results_graph{l}.CVRMSExy_onRangeZ(1, 2),...
                results_graph{l}.meanRMSEz_onRangeZ(1, 2),...
                results_graph{l}.stdRMSEz_onRangeZ(1, 2),...
                results_graph{l}.meanRMSEz_onRangeZ(1, 2)...
                +results_graph{l}.stdRMSEz_onRangeZ(1, 2),...
                results_graph{l}.CVRMSEz_onRangeZ(1, 2),...
                results_graph{l}.min_z_range_metric(3, 1),...
                results_graph{l}.max_z_range_metric(3, 1),...
                results_graph{l}.meanRMSExy_onRangeZ(3, 1),...
                results_graph{l}.stdRMSExy_onRangeZ(3, 1),...
                results_graph{l}.meanRMSExy_onRangeZ(3, 1)...
                +results_graph{l}.stdRMSExy_onRangeZ(3, 1),...
                results_graph{l}.CVRMSExy_onRangeZ(3, 1),...
                results_graph{l}.meanRMSEz_onRangeZ(3, 1),...
                results_graph{l}.stdRMSEz_onRangeZ(3, 1),...
                results_graph{l}.meanRMSEz_onRangeZ(3, 1)...
                +results_graph{l}.stdRMSEz_onRangeZ(3, 1),...
                results_graph{l}.CVRMSEz_onRangeZ(3, 1),...
                results_graph{l}.min_z_range_metric(3, 2),...
                results_graph{l}.max_z_range_metric(3, 2),...
                results_graph{l}.meanRMSExy_onRangeZ(3, 2),...
                results_graph{l}.stdRMSExy_onRangeZ(3, 2),...
                results_graph{l}.meanRMSExy_onRangeZ(3, 2)...
                +results_graph{l}.stdRMSExy_onRangeZ(3, 2),...
                results_graph{l}.CVRMSExy_onRangeZ(3, 2),...
                results_graph{l}.meanRMSEz_onRangeZ(3, 2),...
                results_graph{l}.stdRMSEz_onRangeZ(3, 2),...
                results_graph{l}.meanRMSEz_onRangeZ(3, 2)...
                +results_graph{l}.stdRMSEz_onRangeZ(3, 2),...
                results_graph{l}.CVRMSEz_onRangeZ(3, 2),...
                results_graph{l}.range_metric(1,1),...
                results_graph{l}.range_metric(1,2),...
                results_graph{l}.range_metric(3,1),...
                results_graph{l}.range_metric(3,2),...
                results_graph{l}.max_metric(1),...
                results_graph{l}.min_z_FWHM_metric(1),...
                results_graph{l}.max_z_FWHM_metric(1),...
                results_graph{l}.FWHM(1),...
                results_graph{l}.max_metric(3),...
                results_graph{l}.min_z_FWHM_metric(3),...
                results_graph{l}.max_z_FWHM_metric(3),...
                results_graph{l}.FWHM(3),...
                results_graph{l}.metric_thres(1,1),...
                results_graph{l}.metric_thres(1,2),...
                results_graph{l}.metric_thres(3,1),...
                results_graph{l}.metric_thres(3,2));
        end
    end
    fclose(fileID);
    
end
fprintf('The public assessment results are saved in the file %s in different modality folders\n',fname);
end

function results_graph = fill_results_graph(results)
res_len = length(results);
results_graph = cell(res_len,1);
for l = 1:res_len
    results_graph{l}.dim3D = results{l}.dim3D;
    results_graph{l}.photonT = results{l}.photonT;
    results_graph{l}.wobble = results{l}.wobble;
    results_graph{l}.participant = results{l}.participant;
    results_graph{l}.dataset = results{l}.dataset;
    results_graph{l}.modality = results{l}.modality;
    results_graph{l}.min_z_range_metric = nan(3,2);
    results_graph{l}.max_z_range_metric = nan(3,2);
    results_graph{l}.meanRMSExy_onRangeZ = nan(3,2);
    results_graph{l}.stdRMSExy_onRangeZ = nan(3,2);
    results_graph{l}.CVRMSExy_onRangeZ = nan(3,2);
    results_graph{l}.meanRMSEz_onRangeZ = nan(3,2);
    results_graph{l}.stdRMSEz_onRangeZ = nan(3,2);
    results_graph{l}.CVRMSEz_onRangeZ = nan(3,2);
    results_graph{l}.metric_thres = nan(3,2);
    results_graph{l}.range_metric = nan(3,2);
    results_graph{l}.max_metric = nan(3,1);
    results_graph{l}.min_z_FWHM_metric = nan(3,1);
    results_graph{l}.max_z_FWHM_metric = nan(3,1);
    results_graph{l}.FWHM = nan(3,1);
end
end